### ISSUE TITLE
Is there any alternative to mysql NOW() function?

### ISSUE THREAD

**Issue by me2resh** [luxifer/doctrine-functions#19]
Is there any alternative to mysql NOW() function?

**Comment by luxifer** [comment]
Yes, you have CURRENT_TIMESTAMP which works on sqlite and postgres (it's a
keyword, not a function)

Florent Viel
Le 1 sept. 2015 7:14 AM, "Ahmed Ibrahim" <notifications@github.com> a
écrit :

**Comment by luxifer** [comment]
And it's already implemented by the DQL parser https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Query/Parser.php#L77
