### ISSUE TITLE
PHP 7.X Support Violated

### ISSUE THREAD

**Issue by HeathNaylor** [luxifer/doctrine-functions#25]
It looks like https://github.com/luxifer/doctrine-functions/blob/master/src/DQL/String/ConcatWs.php#L3 possibly violates a reserved word of `string` as defined here: http://php.net/manual/en/reserved.other-reserved-words.php.

Are these reserved words case-insensitive?

**Comment by luxifer** [comment]
As you can see on [travis](https://travis-ci.org/luxifer/doctrine-functions/jobs/319720132) builds for php 7.0, 7.1 and 7.2 are OK so the support is not violated.

Regards.
